#!/bin/sh

DIST_PATH="dist"

cd "$(dirname "$0")"
rm -rf "$DIST_PATH/js/*"
rm -rf "$DIST_PATH/css/*"
rm -rf "$DIST_PATH/manifest.json"
webpack --optimize-minimize

# remove unnecessary js link to styles generated by style entry point.
# See the link below if better solution appears.
# https://stackoverflow.com/questions/45802073/webpack-2-exclude-css-entry-from-result
rm -rf "$DIST_PATH/js/style.*"
